[MAC-1661] add error handling to test

diff --git a/.github/workflows/lokalise-i18n-push.yaml b/.github/workflows/lokalise-i18n-push.yaml
--- a/.github/workflows/lokalise-i18n-push.yaml
+++ b/.github/workflows/lokalise-i18n-push.yaml
@@ -42,7 +42,7 @@ jobs:
             BASE_64_CONTENT="$(base64 -w 0 "$file")"
 
             echo "Uploading $file (lang: $LANG_ISO) with Base64 content: $BASE_64_CONTENT"
-            curl -v "https://api.lokalise.com/api2/projects/$ENV_LOKALISE_PROJECT_ID/files/upload" \
+            RESPONSE=$(curl -v "https://api.lokalise.com/api2/projects/$ENV_LOKALISE_PROJECT_ID/files/upload" \
               --header "x-api-token: $ENV_LOKALISE_API_TOKEN" \
               --header "accept: application/json" \
               --header "content-type: application/json" \
@@ -59,5 +59,15 @@ jobs:
                 \"lang_iso\": \"$LANG_ISO\",
                 \"filename\": \"$file\",
                 \"data\": \"$BASE_64_CONTENT\"
-              }"
+              }")
+
+            RESP_STATUS=$(echo "$RESPONSE" | jq -r '.error.code')
+            RESP_MSG=$(echo "$RESPONSE" | jq -r '.error.message')
+
+            if [ "$RESP_STATUS" -ne 200 ]; then
+              echo "Request failed with status: $RESP_STATUS
+              echo "Error Message:"
+              echo "$RESP_MSG"
+              exit 1
+            fi
           done
