Update sonarqube-scan.yaml

diff --git a/.github/workflows/sonarqube-scan.yaml b/.github/workflows/sonarqube-scan.yaml
--- a/.github/workflows/sonarqube-scan.yaml
+++ b/.github/workflows/sonarqube-scan.yaml
@@ -102,7 +102,8 @@ jobs:
         if: ${{ github.ref != format('refs/heads/{0}', env.REFERENCE_BRANCH) && inputs.is_dotnet_project == true }}
         run: |
           PROJECT_ROOT=$(pwd)
-          sed -i "s| fullPath=\"[^\"]*$PROJECT_ROOT/| fullPath=\"|g" ./TestResults/coverage.opencover.xml
+          sed -i "s| fullPath=\"[^\"]*${PROJECT_ROOT}/| fullPath=\"|g" ./TestResults/coverage.opencover.xml
+          cat ./TestResults/coverage.opencover.xml | grep fullPath
 
       - name: Check coverage file exists
         working-directory: ${{ inputs.working_directory }}
@@ -144,6 +145,13 @@ jobs:
           csproj=$(find . -maxdepth 2 -name '*.csproj' | head -n 1)
           echo "Found project: $csproj"
           dotnet build "$csproj"
+
+      - name: Debug – Sonar files to analyze
+        working-directory: ${{ inputs.working_directory }}
+        if: ${{ github.ref != format('refs/heads/{0}', env.REFERENCE_BRANCH) && inputs.is_dotnet_project == true }}
+        run: |
+          echo "---- FilesToAnalyze.txt ----"
+          cat .sonarqube/conf/0/FilesToAnalyze.txt || echo "Not found"
 
       - name: .NET SonarScanner End
         working-directory: ${{ inputs.working_directory }}
