Update sonarqube-scan.yaml

diff --git a/.github/workflows/sonarqube-scan.yaml b/.github/workflows/sonarqube-scan.yaml
--- a/.github/workflows/sonarqube-scan.yaml
+++ b/.github/workflows/sonarqube-scan.yaml
@@ -96,7 +96,7 @@ jobs:
       - name: Check coverage file exists
         run: |
           ls -la TestResults/
-          cat TestResults/coverage.xml || echo "Coverage file missing or empty"
+          cat coverage.xml || echo "Coverage file missing or empty"
 
       - name: .NET SonarScanner Begin
         if: ${{ github.ref != format('refs/heads/{0}', env.REFERENCE_BRANCH) && inputs.is_dotnet_project == true }}
@@ -109,7 +109,7 @@ jobs:
       - name: .NET SonarScanner End
         if: ${{ github.ref != format('refs/heads/{0}', env.REFERENCE_BRANCH) && inputs.is_dotnet_project == true }}
         run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
-        
+
       - name: Scan
         uses: sonarsource/sonarqube-scan-action@master
         if: ${{ inputs.is_dotnet_project != true && github.ref != format('refs/heads/{0}', env.REFERENCE_BRANCH) }}
